Add World Database on Protected Areas layer
nasa-gibs/worldview-options-eosdis pull request #222
Opened 2018-07-18 15:28 UTC by mike-mcgann

## Description

Fixes nasa-gibs/worldview#603.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if appropriate)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Lint and unit tests pass locally with my changes (`npm run test`)
- [x] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

2018-07-20 17:34 UTC, mike-mcgann commented
Needs a layer description

2018-08-13 20:00 UTC, rboller commented on common/colormaps/wdpa/World_Database_on_Protected_Areas.xml
> +  <ColorMap title="Protected Areas">
This should probably be titled `Protected Area` since it denotes one area at at time.

2018-08-13 20:05 UTC, rboller requested changes
Layer looks good but should be supported in image download.

Also, is this layer also available in EPSG:3413?  I could see it being useful for showing areas in higher latitudes.

Otherwise made one small request for the colormap.

2018-08-14 13:00 UTC, mike-mcgann commented
Changed areas to area and added to epsg:3413. Not sure how we handle image download these days. I'm assuming we enter in a GIBS ticket?

2018-08-14 15:15 UTC, mike-mcgann commented
Ticket GIBS-3129

2018-08-14 17:39 UTC, mike-mcgann commented
GIBS ticket got rejected. Now the ticket is WVS-165.

2018-11-15 16:39 UTC, ZachTRice commented
Closing this ticket. Please refer to equivalent issues in the [worldview](http://github.com/nasa-gibs/worldview) repository.

2018-11-15 16:39 UTC, closed without merging